tick_interval_secs = 1
storage_path = "./temp/events.toml"

[oracle]
addresses = ["varanasi-rpc-url"]

[blockchain]
addresses = ["varanasi-grpc-url"]
contract = "varanasi-parent-asc-contract-address"

[blockchain.signkey]
# It should be either mnemonic or bip32
mnemonic = "mnemonic seed phase"
bip32 = "xprv9s21ZrQH143K3FQVQn1Z6"

[blockchain.fee]
denom = "UAMF"
amount = 3000000

[core]
addresses = ["kms-core-url"]

[core.timeout_config]
channel_timeout = 60

[core.timeout_config.crs]
initial_wait_time = 60
retry_interval = 60
max_poll_count = 120

[core.timeout_config.keygen]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[core.timeout_config.preproc]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[core.timeout_config.decryption]
initial_wait_time = 0
retry_interval = 0
max_poll_count = 1

[core.timeout_config.reencryption]
initial_wait_time = 0
retry_interval = 0
max_poll_count = 1

[tracing]
service_name = "kms-asc-connector"
endpoint = "http://localhost:4317"

[store]
url = "kms-kv-store-url"
